version: "3.8"

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/aradice/data/wordpress
      o: bind
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/aradice/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge

services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    volumes:
      - wordpress_vol:/var/www/
    depends_on:
      - mariadb
    env_file:
      - .env
    ports:
      - "9000:9000"
    networks:
      - inception

  
  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_vol:/var/lib/mysql
    environment:
      - MDB_DBNAME
      - MDB_USER
      - MDB_USER_PASS
      - MDB_ROOT_USER
      - MDB_ROOT_PASS
    ports:
      - 3306:3306
    networks:
      - inception

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    build: requirements/nginx
    volumes:
      - wordpress_vol:/var/www/
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception